name: Build and Release APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Upload APK to GitHub Releases
        uses: ShowMeThe/github_action_release@v0.01
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
